name = "news-keyword-monitor"
main = "src/index.js"
compatibility_date = "2024-09-23"

# 5분마다 자동 실행 (Cron Trigger)
[triggers]
crons = ["*/5 * * * *"]

# 중복 방지 및 키워드 저장을 위한 KV 바인딩
[[kv_namespaces]]
binding = "NEWS_KV"
id = "7c2702a2387c42038fd5f696d2fd8bb9"
