name = "news-keyword-monitor"
main = "src/index.js"
compatibility_date = "2024-09-23"

# 1분마다 트리거를 실행하고, 내부에서 설정된 간격(기본 5분)에 맞춰 실행
[triggers]
crons = ["* * * * *"]

# 중복 방지 및 키워드 저장을 위한 KV 바인딩
[[kv_namespaces]]
binding = "NEWS_KV"
id = "7c2702a2387c42038fd5f696d2fd8bb9"
